---

- name: Create servers
  hosts: localhost
  vars_prompt:
    - name: key_name
      prompt: Key name?
      private: false
    - name: network
      prompt: Network?
      private: false
  roles:
    - instances
    - openstack_facts

- name: Keys
  hosts: created_instances
  become: true
  tasks:
  - name: Set authorized key taken from keys/*
    authorized_key:
      user: "{{ ssh_user }}"
      state: present
      key: "{{ lookup('file', item) }}"
    with_fileglob: "keys/*"

- name: Configure VMs
  hosts: created_instances
  gather_facts: false
  become: true
  roles:
  - hosts
  - glusterfs
