---

- name: Install GPG keys
  yum:
    name:
      - centos-release-storage-common
    state: present

- name: Install GlusterFS v11 repository
  become: yes
  yum_repository:
    name: gluster11
    description: Gluster FS v11
    baseurl: https://buildlogs.centos.org/centos/9-stream/storage/x86_64/gluster-11/
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-SIG-Storage

#- name: install updates
#  yum: update_cache=yes

- name: Ensure the crb repository is enabled
  community.general.dnf_config_manager:
    name: crb
    state: enabled

- name: Install GlusterFS
  yum:
    name:
      - glusterfs-server
    state: present

- name: Enable and start Glusterd
  service:
    name: glusterd
    enabled: yes
    state: started

- name: Set IPs
  set_fact:
    gluster_ips: "{{ groups['all'] | map('extract', hostvars, ['ansible_host']) }}"

- name: Create a trusted storage pool
  gluster.gluster.gluster_peer:
    state: present
    nodes: "{{ gluster_ips }}"

- name: Create a xfs filesystem on /dev/sdb
  filesystem:
    fstype: xfs
    dev: /dev/vdb

- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: /data/brick1/
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Mount brick folder
  ansible.posix.mount:
    path: /data/brick1/
    src: /dev/vdb
    fstype: xfs
    state: mounted

- name: Create brick directory
  ansible.builtin.file:
    path: /data/brick1/gv0
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Create gluster volume
  gluster.gluster.gluster_volume:
    state: present
    name:  gv0
    bricks: /data/brick1/gv0
    rebalance: yes
    cluster: "{{ gluster_ips }}"
  run_once: true

- name: start gluster volume
  gluster.gluster.gluster_volume:
    state: started
    name: gv0
