---
- name: Register openstack servers facts
  openstack.cloud.server_info:
    filters:
      metadata:
        group: "{{ item }}"
  register: server_facts
  with_items:
    - "{{ instance_name }}"

# - name: Check
#   debug:
#     msg: "{{ server_facts }}"

- name: Building inventory
  add_host:
    name: "{{ item.name }}"
    groups: created_instances
    ansible_host: "{{ item.addresses[network][0].addr }}"
    ansible_user: almalinux
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o 'ProxyCommand ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -W %h:%p {{ ssh_user }}@{{ jumpHostIP }}' "
  with_items:
    - "{{ server_facts.results[0].servers }}"
